import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Luanle",
      email: "abcde@gmail.com",
      password: bcrypt.hashSync("admin"),
      isAdmin: true,
    },
    {
      name: "Luanle1",
      email: "abcdefgh@gmail.com",
      password: bcrypt.hashSync("ricpe"),
      isAdmin: false,
    },
  ],
  sliderItems: [
    {
      // _id: 1,
      image: "/images/slider/1.jpg",
    },
    {
      // _id: 2,
      image: "/images/slider/logo.jpg",
    },
    {
      // _id: 3,
      image: "/images/slider/2.jpg",
    },
    {
      // _id: 4,
      image: "/images/slider/3.jpg",
    },
    {
      // _id: 5,
      image: "/images/slider/4.jpg",
    },
  ],
  categoryItems: [
    {
      // _id: 1,
      title: "Men",
      image: "/images/category/men.jpg",
    },
    {
      // _id: 2,
      title: "Women",
      image: "/images/category/women.jpg",
    },
    {
      // _id: 3,
      title: "Kids",
      image: "/images/category/kid.jpg",
    },
  ],
  products: [
    {
      // _id: 1,
      title: "Product 1",
      slug: "product1",
      desc: "Description for Product 1",
      category: "Men",
      image: "/images/products/5.jpg",
      image1: "/images/products/6.jpg",
      image2: "/images/products/7.jpg",
      image3: "/images/products/8.jpg",
      countInStock: 0,
      price: "80.00",
    },
    {
      // _id: 2,
      title: "Product 2",
      slug: "product2",
      desc: "Description for Product 2",
      category: "Women",
      image: "/images/products/1.jpg",
      image1: "/images/products/2.jpg",
      image2: "/images/products/3.jpg",
      image3: "/images/products/4.jpg",
      countInStock: 10,
      price: "65.00",
    },
    {
      // _id: 3,
      title: "Product 3",
      slug: "product3",
      desc: "Description for Product 3",
      category: "Kids",
      image: "/images/products/10.jpg",
      image1: "/images/products/11.jpg",
      image2: "/images/products/12.jpg",
      image3: "/images/products/13.jpg",
      countInStock: 15,
      price: "72.00",
    },
    {
      // _id: 4,
      title: "Product 4",
      slug: "product4",
      desc: "Description for Product 4",
      category: "Women",
      image: "/images/products/19.jpg",
      image1: "/images/products/20.jpg",
      image2: "/images/products/21.jpg",
      image3: "/images/products/22.jpg",
      countInStock: 20,
      price: "92.00",
    },
    {
      // _id: 5,
      title: "Product 5",
      slug: "product5",
      desc: "Description for Product 3",
      category: "Kids",
      image: "/images/products/23.jpg",
      image1: "/images/products/24.jpg",
      image2: "/images/products/25.jpg",
      image3: "/images/products/26.jpg",
      countInStock: 25,
      price: "72.00",
    },
    {
      // _id: 6,
      title: "Product 6",
      slug: "product6",
      desc: "Description for Product 4",
      category: "Women",
      image: "/images/products/15.jpg",
      image1: "/images/products/16.jpg",
      image2: "/images/products/17.jpg",
      image3: "/images/products/18.jpg",
      countInStock: 30,
      price: "92.00",
    },
    {
      // _id: 7,
      title: "Product 7",
      slug: "product7",
      desc: "Description for Product 1",
      category: "Men",
      image: "/images/products/7.jpg",
      image1: "/images/products/8.jpg",
      image2: "/images/products/9.jpg",
      image3: "/images/products/10.jpg",
      countInStock: 35,
      price: "80.00",
    },
    {
      // _id: 8,
      title: "Product 8",
      slug: "product8",
      desc: "Description for Product 1",
      category: "Men",
      image: "/images/products/27.jpg",
      image1: "/images/products/28.jpg",
      image2: "/images/products/29.jpg",
      image3: "/images/products/30.jpg",
      countInStock: 40,
      price: "80.00",
    },
  ],
};

export default data;
