import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Luanle",
      email: "abcde@gmail.com",
      password: bcrypt.hashSync("admin"),
      isAdmin: true,
    },
    {
      name: "Luanle1",
      email: "abcdefgh@gmail.com",
      password: bcrypt.hashSync("ricpe"),
      isAdmin: false,
    },
  ],
  sliderItems: [
    {
      // _id: 1,
      image: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737291/images/slider/1_okjgel.jpg",
    },
    {
      // _id: 2,
      image: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737289/images/slider/3_kzwygo.webp",
    },
    {
      // _id: 3,
      image: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737289/images/slider/2_wzxwwr.jpg",
    },
    {
      // _id: 4,
      image: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737289/images/slider/3_kzwygo.webp",
    },
    {
      // _id: 5,
      image: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737289/images/slider/4_vi5xz9.png",
    },
  ],
  categoryItems: [
    {
      // _id: 1,
      title: "Men",
      image: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737380/images/category/men_zbdiap.webp",
    },
    {
      // _id: 2,
      title: "Women",
      image: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737380/images/category/women_rwbchh.jpg",
    },
    {
      // _id: 3,
      title: "Kids",
      image: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737381/images/category/kid_syuqwf.jpg",
    },
  ],
  products: [
    {
      // _id: 1,
      title: "Product 1",
      slug: "product1",
      desc: "Description for Product 1",
      category: "Men",
      image: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737311/images/products/5_rcka3q.webp",
      image1: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737311/images/products/6_eilq4t.jpg",
      image2: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737311/images/products/7_uinued.jpg",
      image3: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737311/images/products/8_kch71z.jpg",
      countInStock: 0,
      price: "80.00",
    },
    {
      // _id: 2,
      title: "Product 2",
      slug: "product2",
      desc: "Description for Product 2",
      category: "Women",
      image: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737310/images/products/1_cwklmu.jpg",
      image1: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737310/images/products/2_ltqa1p.jpg",
      image2: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737310/images/products/3_whewrp.jpg",
      image3: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737310/images/products/4_scvnym.jpg",
      countInStock: 10,
      price: "65.00",
    },
    {
      // _id: 3,
      title: "Product 3",
      slug: "product3",
      desc: "Description for Product 3",
      category: "Kids",
      image: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737311/images/products/10_e1qxr6.webp",
      image1: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737311/images/products/11_dyxjbq.jpg",
      image2: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737311/images/products/12_kjgqnb.jpg",
      image3: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737312/images/products/13_cag0v6.jpg",
      countInStock: 15,
      price: "72.00",
    },
    {
      // _id: 4,
      title: "Product 4",
      slug: "product4",
      desc: "Description for Product 4",
      category: "Women",
      image: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737312/images/products/19_io1tfl.jpg",
      image1: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737313/images/products/20_pmzbj8.jpg",
      image2: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737313/images/products/21_hunovr.jpg",
      image3: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737313/images/products/22_eiukk5.jpg",
      countInStock: 20,
      price: "92.00",
    },
    {
      // _id: 5,
      title: "Product 5",
      slug: "product5",
      desc: "Description for Product 3",
      category: "Kids",
      image: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737313/images/products/23_vcunmt.jpg",
      image1: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737313/images/products/24_hrersk.jpg",
      image2: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737314/images/products/25_fwf5u3.jpg",
      image3: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737314/images/products/26_g8gj5x.jpg",
      countInStock: 25,
      price: "72.00",
    },
    {
      // _id: 6,
      title: "Product 6",
      slug: "product6",
      desc: "Description for Product 4",
      category: "Women",
      image: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737313/images/products/15_ededat.jpg",
      image1: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737312/images/products/16_pk84gz.jpg",
      image2: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737312/images/products/17_purhf0.jpg",
      image3: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737313/images/products/18_ahoaho.jpg",
      countInStock: 30,
      price: "92.00",
    },
    {
      // _id: 7,
      title: "Product 7",
      slug: "product7",
      desc: "Description for Product 1",
      category: "Men",
      image: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737311/images/products/7_uinued.jpg",
      image1: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737311/images/products/8_kch71z.jpg",
      image2: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737311/images/products/9_b4ka7j.webp",
      image3: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737311/images/products/10_e1qxr6.webp",
      countInStock: 35,
      price: "80.00",
    },
    {
      // _id: 8,
      title: "Product 8",
      slug: "product8",
      desc: "Description for Product 1",
      category: "Men",
      image: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737314/images/products/27_s9ai0m.jpg",
      image1: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737314/images/products/28_jt0eyl.jpg",
      image2: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737314/images/products/29_erap8p.jpg",
      image3: "https://res.cloudinary.com/dzevej4xd/image/upload/v1663737314/images/products/30_mtn8f7.jpg",
      countInStock: 40,
      price: "80.00",
    },
  ],
};

export default data;
